### ISSUE TITLE
Add Boot Strap

### ISSUE THREAD

**Issue by MotoAcidic** [scryptachain/scrypta#15]
Adding a boot strap option for users to select instead of downloading the whole chain from the genesis hash could help newer users or people who haven't opened their wallet in a while sync it much quicker.

**Comment by turinglabsorg** [comment]
New service created, fresh bootstrap will be generated every 10 minutes here: http://bootstrap.scryptachain.org/latest.zip

**Comment by MotoAcidic** [comment]
Full feature to download and install the bootstrap through gui and cli is here https://github.com/MotoAcidic/scrypta/commit/aa7974bae3fd44f38708df335149d07cd9d8cc41
