### ISSUE TITLE
[WIN] How to build for Windows

### ISSUE THREAD

**Issue by 0xChupaCabra** [scryptachain/scrypta#20]
sudo apt-get auto-remove && sudo apt-get clean && sudo apt-get update && sudo apt-get upgrade
cd scripts
chmod +x *.sh
sudo ./build-win64.sh
cd ..
sudo ./autogen.sh && sudo ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 && sudo make

**Comment by cryptojoystick** [comment]
Following this commands on Ubuntu 16 and still getting errors. 
Stopped after "sudo ./build-win64.sh" with

Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
sudo: ./configure: comando non trovato
make: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
Remember to strip the QT file!

**Comment by MotoAcidic** [comment]
If you are getting the ltmain.sh not found try this

```
sudo libtoolize --automake --copy --debug --force
sudo autoreconf -i
sudo ./autogen.sh
```
