### ISSUE TITLE
[fix] change text on bootstrap window

### ISSUE THREAD

**Issue by 0xChupaCabra** [scryptachain/scrypta#21]
Showing "Galilel core" during bootstrap download

**Comment by MotoAcidic** [comment]
Removed the Galilel files that where not needed from the bootstrap feature and fixed the incorrect references to Galilel to Scrypta.
PR fixing this issues here:  https://github.com/MotoAcidic/scrypta/commit/79d02258c2eafccd49f9d653a790c271175fe03a
