### ISSUE TITLE
[MAC] failed to build for Mac

### ISSUE THREAD

**Issue by 0xChupaCabra** [scryptachain/scrypta#22]
ubuntu 16.04:
make -j4 HOST=x86_64-apple-darwin11

Building native_biplist...
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import ez_setup
ImportError: No module named ez_setup
funcs.mk:242: recipe for target '/root/lyra_test/scrypta/depends/work/build/x86_64-apple-darwin11/native_biplist/0.9-b94d89ead06/./.stamp_built' failed
make: *** [/root/lyra_test/scrypta/depends/work/build/x86_64-apple-darwin11/native_biplist/0.9-b94d89ead06/./.stamp_built] Error 1

**Comment by MotoAcidic** [comment]
Can you show more of the debug log so i can see above this where the error is happening.

**Comment by MotoAcidic** [comment]
Duplicate issues opened on #17

Try to compile https://github.com/MotoAcidic/scrypta/commit/594699f1f9ef5a8d190c75786ad0063cdcf6b716

Please upload debug log a good amount if errors are present.
